### ISSUE TITLE
Sidebar improvement on document page

### ISSUE THREAD

**Issue by akirakw** [asakusafw/asakusafw#474]
Sidebar improvement of document page as follows...
* Fixing sidebar area when scrolling main area
* Highlight current section of sidebar when scrolling main area

Just like following sites layout...
* http://netty.io/wiki/user-guide-for-5.x.html
* https://pythonhosted.org/cloud_sptheme/cloud_theme.html

**Comment by cocoatomo** [comment]
PyPI のページはここでした > https://pypi.python.org/pypi/cloud_sptheme/1.6

**Comment by cocoatomo** [comment]
このサイドバーの動きを実現している JavaScript コードはここでした > https://bitbucket.org/ecollins/cloud_sptheme/src/489149130593bb4013ee630d1a98d50134011482/cloud_sptheme/themes/cloud/static/cloud.js_t?at=default#cl-269

**Comment by cocoatomo** [comment]
Sphinx のページ (http://sphinx-doc.org/index.html) では Sphinx13 というテーマを使っていて, そこでの実現方法も JavaScript でした. > https://github.com/sphinx-doc/sphinx/blob/master/doc/_themes/sphinx13/layout.html#L28-L55

**Comment by akirakw** [comment]
@cocoatomo thanks for your contribution. I forgot to close the issue, closing it now!
